// <auto-generated />
using System;
using FootballCatalog30.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootballCatalog30.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241215205545_CascadeDelPlayerWhenDelCommand")]
    partial class CascadeDelPlayerWhenDelCommand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootballCatalog30.Api.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Россия"
                        },
                        new
                        {
                            Id = 2,
                            Title = "США"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Италия"
                        });
                });

            modelBuilder.Entity("FootballCatalog30.Api.Models.FootballCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Зенит"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Локомотив"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Даллас"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Милан"
                        });
                });

            modelBuilder.Entity("FootballCatalog30.Api.Models.FootballPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CommandId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("CountryId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1997, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CommandId = 1,
                            CountryId = 1,
                            Name = "Александр",
                            Sex = 0,
                            Surname = "Соболев"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1987, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CommandId = 1,
                            CountryId = 1,
                            Name = "Михаил",
                            Sex = 0,
                            Surname = "Кержаков"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1997, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CommandId = 2,
                            CountryId = 1,
                            Name = "Илья",
                            Sex = 0,
                            Surname = "Самошников"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CommandId = 3,
                            CountryId = 2,
                            Name = "Хесус",
                            Sex = 0,
                            Surname = "Феррейра"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1992, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CommandId = 4,
                            CountryId = 3,
                            Name = "Альваро",
                            Sex = 0,
                            Surname = "Мората"
                        });
                });

            modelBuilder.Entity("FootballCatalog30.Api.Models.FootballPlayer", b =>
                {
                    b.HasOne("FootballCatalog30.Api.Models.FootballCommand", "Command")
                        .WithMany("Players")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballCatalog30.Api.Models.Country", "Country")
                        .WithMany("Players")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FootballCatalog30.Api.Models.Country", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootballCatalog30.Api.Models.FootballCommand", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
